CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS urls (
    id SERIAL PRIMARY KEY,
    original_url TEXT NOT NULL,
    short_code VARCHAR(50) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE urls ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS logs (
    id SERIAL PRIMARY KEY,
    short_code VARCHAR(50) NOT NULL,
    action VARCHAR(50) NOT NULL,
    ip_address VARCHAR(100),
    user_agent TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Index for fast lookup
CREATE INDEX IF NOT EXISTS idx_urls_short_code ON urls(short_code);
CREATE INDEX IF NOT EXISTS idx_logs_short_code ON logs(short_code);
CREATE TABLE IF NOT EXISTS reports (
    id SERIAL PRIMARY KEY,
    short_code VARCHAR(50) NOT NULL,
    reason TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_reports_short_code ON reports(short_code);

ALTER TABLE logs ADD COLUMN IF NOT EXISTS location VARCHAR(255);

ALTER TABLE reports ADD COLUMN IF NOT EXISTS reporter_name VARCHAR(100);
ALTER TABLE reports ADD COLUMN IF NOT EXISTS reporter_email VARCHAR(150);
ALTER TABLE reports ADD COLUMN IF NOT EXISTS report_type VARCHAR(50);
