name: lint.yml
on:
  push:
      branches: [ main, staging ]
  pull_request:
      branches: [ main, staging ]

jobs:
  lint:
    name: Golangci lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 1.26.5
      - name: Run lint test
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12